apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hello-world
spec:
  encryptedData:
    .dockerconfigjson: AgAxvUcEnloQIihpkG8zybXaL4k0+rj6h++loeeOWGw+tCcVwJcX/yRaSSMyOU48zUIbzozpsYIiJ1TuvtDX8mnQNK/cz9R/ynYGPuKRhwrOL8q+vwGjfJeDrVQfXBILrD6LVOp31kN11wPFg80SZTMJnRhslAXx1KXk5F+5U9U76f4NVLvikOV3aoo7cmeUvfsxUkLvcoxBaRX9YxzfYk3Y5DW2j+cQKpJ5fYpzKQm7Q+Yme1t/FCHQqiYNca5GNLXf3BeuohoRyy2+/j+jfkm1zJrhn+YUg48QL13yQHwe/CtDwtWhroNp7ReBf1VvMtA7OOoZitkTnyeW2LRaSKG+TR5MDr3xteauLtXk/gil5X0ex3xcH5ImwTdFy/sumd7Zz3dPTYKVoOmfD/T+5mdoVB107x1McOGMayxzYoK+2atLjdfpoymuYEYLPnixPalqgAe6zpfehRYDkStJc2NOSLmMmWgMxD9sXZN1h5P0PQPisErMjZmocEwqNcNXP/TzoxtFkE0lnC8p8w1XYVAid6PvI0uLsI+7O+1YJ0iV/EXxt3rrPRM73MpOeQCCyA6Krhtij/CspJoFsdmJMrjUtnGNz6UViZZBxNA15w7uWTdEkv5XuZRhV07ktSg0NvpdnGTDERx/kobGwW5S1n+rqRwFLz9fCYFuzwb4piSJ5MDFmvROQHZiKKMtFjl9vdw3QrPspacFqecJHdWmZfhkqVfWxM8YZzlnbgnFs0V/88Jj/vGr5e1jV68hiAlRTlvzDOWImSGNTajf9jukRfVPB6NWylBrpEim/lPX52wCYtn/MgVSOt7CLl3uV6t/YVNTe2PKSBDjAF6tKEhbKmks+aR9ZYYAYecC9pMh4UOgj1VE1TiuPXUdvB/Ee7J58IA4UA7kWH7wpOyuVG77NjQN9CKPsQOCC14OAv4UW8gPzqMxhW3YL9HV
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hello-world
    type: kubernetes.io/dockerconfigjson

